[package]
name = "kwordle"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/perpetualcacophony/kwordle"
readme = "README.md"
license-file = "LICENSE.md"

[dependencies]
rand = { version = "0.8.5", optional = true }

[dev-dependencies]
assert-impl = "0.1.3"

[features]
default = ["rand"]
